DesktopResponsive={"1009":{
"pageLayer":{"w":1009,"h":662,"bgColor":"#fffaf5"}
,
"webwidget122321":{"x":0,"y":21,"w":1008,"h":608,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
