DesktopResponsive={"1009":{
"pageLayer":{"w":1338,"h":738,"bgColor":"#fffaf5"}
,
"webwidget121938":{"x":0,"y":0,"w":1337,"h":741,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
