TabletResponsive={"1009":{
"pageLayer":{"w":1009,"h":662,"bgColor":"#fffaf5"}
,
"anim121954":{"x":81,"y":6,"w":860,"h":544,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"785":{
"pageLayer":{"w":785,"h":527,"bgColor":"#fffaf5"}
,
"anim121954":{"x":63,"y":8,"w":669,"h":424,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
