PhoneResponsive={"785":{
"pageLayer":{"w":785,"h":527,"bgColor":"#fffaf5"}
,
"webwidget122321":{"x":0,"y":16,"w":784,"h":473,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"480":{
"pageLayer":{"w":480,"h":560,"bgColor":"#fffaf5"}
,
"webwidget122321":{"x":0,"y":21,"w":480,"h":289,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
