PhoneResponsive={"785":{
"pageLayer":{"w":785,"h":527,"bgColor":"#fffaf5"}
,
"webwidget121938":{"x":0,"y":0,"w":784,"h":435,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"480":{
"pageLayer":{"w":480,"h":763,"bgColor":"#fffaf5"}
,
"webwidget121938":{"x":0,"y":0,"w":480,"h":266,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
