PhoneResponsive={"785":{
"pageLayer":{"w":785,"h":527,"bgColor":"#fffaf5"}
,
"anim121954":{"x":63,"y":5,"w":669,"h":424,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"480":{
"pageLayer":{"w":480,"h":763,"bgColor":"#fffaf5"}
,
"anim121954":{"x":38,"y":8,"w":409,"h":259,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
