DesktopResponsive={"1009":{
"pageLayer":{"w":1338,"h":738,"bgColor":"#fffaf5"}
,
"anim121954":{"x":107,"y":8,"w":1141,"h":722,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
