TabletResponsive={"1009":{
"pageLayer":{"w":1009,"h":662,"bgColor":"#fffaf5"}
,
"webwidget121938":{"x":0,"y":0,"w":1008,"h":559,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
},
"785":{
"pageLayer":{"w":785,"h":527,"bgColor":"#fffaf5"}
,
"webwidget121938":{"x":0,"y":0,"w":784,"h":435,"bOffBottom":0}
,
"RCDResetQuestion":function(){
try{if(window.dragMgr)window.dragMgr.clearDropZones();}catch(e){if(e&&e.message)console.log(e.message);}
}
,
"RCDResultResize":function(){}
,"preload":[]
}}
